### ISSUE TITLE
Assertion failed: Refactorings should be invoked inside transaction

### ISSUE THREAD

**Issue by JoshMcguigan** [kingsollyu/IntelliJ-Plugin-TouchBarSupport#1]
Thank you very much for making this plugin. I'm getting the following exception after using the touchbar within Intellij 2017.3 on OSX 10.13.3.

Assertion failed: Refactorings should be invoked inside transaction
java.lang.Throwable: Assertion failed: Refactorings should be invoked inside transaction
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:172)
	at com.intellij.refactoring.ui.RefactoringDialog.show(RefactoringDialog.java:66)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:198)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:169)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:119)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:79)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:131)
	at com.sollyu.java.idea.button.RenameTouchBarItem.run(RenameTouchBarItem.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kingsollyu** [comment]
i got the problem, i'll fix it on tomorrow by bingjing timezone.
您好，问题我已经看到，我尽量在明天修正（北京时间）

sorry for my english, the english by translate.
我的英文很差，上面的语句来自机器翻译。

**Comment by EeeMt** [comment]
不用老是sorry for your English  , 大家看得懂就行, 看不懂大不了多解释一遍, 哈哈哈哈

**Comment by kingsollyu** [comment]
但是我英语不好，我也不知道这么回复
